#pragma once

namespace lc {

#define LC_KILLAURA_SETTINGS "\"killaura\",\"killauracpsmode\",\"killauramode\",\"killaurasort\",\"killauraautoblock\",\"killauraattacktick\",\"killauraautoblockrequirepress\",\"killauraautoblockcps\",\"killauraautoblockrange\",\"killauraswingrange\",\"killauraattackrange\",\"killaurafov\",\"killauramincps\",\"killauramaxcps\",\"killauraswitchdelay\",\"killaurarotations\",\"killauradeadzone\",\"killauramaxturnspeed\",\"killauraminturnspeed\",\"killauraacceleration\",\"killauradeceleration\",\"killaurauseovershoot\",\"killauraovershootstrength\",\"killauraovershootrecovery\",\"killauranoisestrength\",\"killauravisualizeaim\",\"killaurasmoothback\",\"killauramovefix\",\"killaurasmoothing\",\"killauraravensmoothing\",\"killauraravenpredictticks\",\"killauraravenyawrandom\",\"killauraanglestep\",\"killaurathroughwalls\",\"killaurarequirepress\",\"killauraallowmining\",\"killauraweaponsonly\",\"killauraallowtools\",\"killaurainventorycheck\",\"killaurabotcheck\",\"killauraplayers\",\"killaurabosses\",\"killauramobs\",\"killauraanimals\",\"killauragolems\",\"killaurasilverfish\",\"killaurateams\",\"killaurashowtarget\",\"killauradebug\",\"killaurarandomize\",\"killaurarandomizerange\",\"killaurayrandomize\",\"killauralbhorizontalspeed\",\"killauralbverticalspeed\",\"killauralbsmooth\",\"killauralbpredict\",\"killauralbpredictsize\",\"killauralbrandomize\",\"killauralbrandomrange\",\"killauralbhorizontalsearch\",\"killauralbbodymin\",\"killauralbbodymax\""

inline const char* LegacyCapabilitiesJson()
{
    return
        "{\"type\":\"capabilities\","
        "\"modules\":[\"autoclicker\",\"rightclick\",\"jitter\",\"clickinchests\",\"breakblocks\",\"aimassist\",\"killaura\",\"speedbridge\",\"gtbhelper\",\"nametags\",\"nickhider\",\"closestplayer\",\"fightstatus\",\"chestesp\",\"cheststealer\",\"blockesp\",\"reach\",\"velocity\",\"antidebuff\",\"hitdelayfix\",\"pixelpartyassist\",\"hudeditor\"],"
        "\"settings\":[\"mincps\",\"maxcps\",\"left\",\"right\",\"rightmincps\",\"rightmaxcps\",\"rightblock\",\"breakblocks\",\"jitter\",\"clickinchests\",\"aimassistfov\",\"aimassistrange\",\"aimassiststrength\"," LC_KILLAURA_SETTINGS ",\"speedbridge\",\"speedbridgeblockonly\",\"speedbridgedelayms\",\"speedbridgeholdingshiftonly\",\"speedbridgelookingdownonly\",\"nametags\",\"nickhiderenabled\",\"nickhideralias\",\"closestplayerinfo\",\"fightstatus\",\"keybindfightstatus\",\"nametagshowhealth\",\"nametagshowarmor\",\"nametaghidevanilla\",\"nametagmaxcount\",\"chestesp\",\"chestespmaxcount\",\"cheststealerenabled\",\"cheststealerdelayms\",\"blockespenabled\",\"blockespboxes\",\"blockesptracers\",\"blockesphud\",\"blockespmaxcount\",\"blockesprange\",\"blockespblocks\",\"keybindblockesp\",\"reachenabled\",\"reachmin\",\"reachmax\",\"reachchance\",\"velocityenabled\",\"velocityhorizontal\",\"velocityvertical\",\"velocitychance\",\"antidebuffenabled\",\"hitdelayfixenabled\",\"gtbhint\",\"gtbcount\",\"gtbpreview\",\"showmodulelist\",\"moduleliststyle\",\"showlogo\",\"guitheme\",\"keybindautoclicker\",\"keybindspeedbridge\",\"keybindnametags\",\"keybindclosestplayer\",\"keybindchestesp\",\"keybindcheststealer\",\"pixelpartyassist\",\"pixelpartyscanradius\",\"pixelpartyautolook\",\"pixelpartyautowalk\",\"hudeditor\"],"
        "\"state\":[\"actionbar\",\"holdingblock\",\"lookingatblock\",\"lookingatentity\",\"lookingatentitylatched\",\"breakingblock\",\"attackcooldown\",\"attackcooldownpertick\",\"killauraunavailablereason\",\"killaurahastarget\",\"killaurablocking\",\"statems\",\"cheststealerstate\",\"pitch\",\"pixelpartytargetfound\",\"pixelpartytargetyaw\",\"pixelpartytargetdist\",\"pixelpartyyawdelta\",\"hudlayout\"]}\n";
}

inline const char* ModernCapabilitiesJson()
{
    return
        "{\"type\":\"capabilities\","
        "\"modules\":[\"autoclicker\",\"rightclick\",\"jitter\",\"clickinchests\",\"breakblocks\",\"aimassist\",\"triggerbot\",\"killaura\",\"speedbridge\",\"gtbhelper\",\"nametags\",\"nickhider\",\"closestplayer\",\"fightstatus\",\"chestesp\",\"cheststealer\",\"blockesp\",\"reach\",\"velocity\",\"autototem\",\"antidebuff\",\"hitdelayfix\",\"pixelpartyassist\",\"hudeditor\"],"
        "\"settings\":[\"mincps\",\"maxcps\",\"left\",\"right\",\"rightmincps\",\"rightmaxcps\",\"rightblock\",\"breakblocks\",\"jitter\",\"clickinchests\",\"triggerbot\"," LC_KILLAURA_SETTINGS ",\"speedbridge\",\"speedbridgeblockonly\",\"speedbridgedelayms\",\"speedbridgeholdingshiftonly\",\"speedbridgelookingdownonly\",\"gtbhint\",\"gtbcount\",\"gtbpreview\",\"nametags\",\"nickhiderenabled\",\"nickhideralias\",\"closestplayerinfo\",\"fightstatus\",\"keybindfightstatus\",\"nametagshowhealth\",\"nametagshowarmor\",\"nametaghidevanilla\",\"nametagmaxcount\",\"chestesp\",\"chestespmaxcount\",\"cheststealerenabled\",\"cheststealerdelayms\",\"blockespenabled\",\"blockespboxes\",\"blockesptracers\",\"blockesphud\",\"blockespmaxcount\",\"blockesprange\",\"blockespblocks\",\"keybindblockesp\",\"reachenabled\",\"reachmin\",\"reachmax\",\"reachchance\",\"velocityenabled\",\"velocityhorizontal\",\"velocityvertical\",\"velocitychance\",\"reloadmappingsnonce\",\"showmodulelist\",\"moduleliststyle\",\"showlogo\",\"guitheme\",\"autototemenabled\",\"autototemmode\",\"autototemhealth\",\"autototemelytra\",\"autototemexplosion\",\"autototemfall\",\"autototemdelay\",\"antidebuffenabled\",\"hitdelayfixenabled\",\"pixelpartyassist\",\"pixelpartyscanradius\",\"pixelpartyautolook\",\"pixelpartyautowalk\",\"hudeditor\"],"
        "\"state\":[\"actionbar\",\"holdingblock\",\"lookingatblock\",\"lookingatentity\",\"lookingatentitylatched\",\"breakingblock\",\"attackcooldown\",\"attackcooldownpertick\",\"killauraunavailablereason\",\"killaurahastarget\",\"killaurablocking\",\"statems\",\"cheststealerstate\",\"pixelpartytargetfound\",\"pixelpartytargetyaw\",\"pixelpartytargetdist\",\"pixelpartyyawdelta\",\"hudlayout\"]}\n";
}

} // namespace lc
